import { Ionicons } from "@expo/vector-icons";

// Peta nama "makna" → icon Ionicons, biar gampang dipakai & konsisten.
const MAP: any = {
  location: "location",
  pin: "location-sharp",
  map: "map-outline",
  route: "navigate-outline",
  clock: "time-outline",
  timer: "timer-outline",
  hourglass: "hourglass-outline",
  calendar: "calendar-outline",
  refresh: "refresh",
  sync: "sync-outline",
  check: "checkmark-circle",
  checkDone: "checkmark-done-outline",
  warn: "alert-circle",
  info: "information-circle-outline",
  trash: "trash-outline",
  user: "person-outline",
  users: "people-outline",
  userPlus: "person-add-outline",
  cash: "cash-outline",
  wallet: "wallet-outline",
  bill: "receipt-outline",
  card: "card-outline",
  box: "cube-outline",
  cart: "cart-outline",
  clipboard: "clipboard-outline",
  trend: "trending-up-outline",
  search: "search",
  filter: "funnel-outline",
  sort: "swap-vertical-outline",
  plus: "add",
  minus: "remove",
  back: "chevron-back",
  chevron: "chevron-forward",
  chevronDown: "chevron-down",
  home: "home-outline",
  store: "storefront-outline",
  doc: "document-text-outline",
  chart: "bar-chart-outline",
  pie: "pie-chart-outline",
  chat: "chatbubbles-outline",
  send: "send",
  bell: "notifications-outline",
  key: "key-outline",
  lock: "lock-closed-outline",
  logout: "log-out-outline",
  camera: "camera-outline",
  image: "image-outline",
  phone: "call-outline",
  whatsapp: "logo-whatsapp",
  edit: "create-outline",
  download: "download-outline",
  upload: "cloud-upload-outline",
  share: "share-social-outline",
  print: "print-outline",
  close: "close",
  closeCircle: "close-circle",
  settings: "settings-outline",
  shield: "shield-checkmark-outline",
  list: "list-outline",
  grid: "grid-outline",
  eye: "eye-outline",
  eyeOff: "eye-off-outline",
  save: "save-outline",
  flag: "flag-outline",
  star: "star-outline",
  build: "construct-outline",
};

export default function AppIcon({ name, size = 16, color = "#111", style }: any) {
  // Nama tak dikenal → tampilkan tanda tanya (biar salah ketik langsung kelihatan,
  // bukan ikon kosong).
  const glyph = MAP[name] ?? (typeof name === "string" && name.includes("-") ? name : "help-circle-outline");
  return <Ionicons name={glyph} size={size} color={color} style={style} />;
}
